name = "lightrepo"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "lightburnpros-db"
database_id = "bd085b36-d252-4c28-8534-1660efd3b967"
migrations_dir = "drizzle"
